#logback
logging:
  config: classpath:logback.xml
  level:
    com.CloudWhite.PersonalBlog.Dao: trace  # ???????????
#    org.hibernate.sql: DEBUG
#????
server:
  port: 8081
spring:
  application:
    name: PersonalBlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personalblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      max-lifetime: 1770000
      maximum-pool-size: 4
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  #    show-sql: true
  #redis
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
      jedis:
        pool:
          max-idle: 1000
          min-idle: 0
          max-active: -1
          max-wait: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  #web
  web:
    resources:
      static-locations: file:./uploads/
  mvc:
    static-path-pattern: /uploads/**

#mybatis
mybatis:
  type-aliases-package: com.CloudWhite.PersonalBlog.Entity
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #用来显示sql