# ???
# server:
#  port: 8080 # ???
#  address: localhost # ??
#url: http://localhost:8002 # ???????????
# ??????,?????????????
#logback
logging:
  config: classpath:logback.xml  # ??logback??????
  level:
    com.WhiteCloud.SpringBootTest.Dao: trace # ???????????
# mybatis
spring:
  application:
    name: SpringBootTest
  datasource:
    driver: com.mysql.cj.driver
    url: jdbc:mysql://localhost:3306/usermanagesystem?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari: #???????
      maximum-pool-size: 10 # ??????
      max-lifetime: 1770000
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/WhiteCloud/SpringBootTest/Entity
# spring-doc
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

