server:
  port: 8761
spring:
  application:
    name: Eureka-Server
eureka:
  instance:
    hostname: localhost  # ???????????????????/??IP???
  client:
    register-with-eureka: false  # ?????????????
    fetch-registry: false        # ????????????
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # ??????
  server:
    enable-self-preservation: false  # ???????????true?????????false
    eviction-interval-timer-in-ms: 60000  # ????????????????
    renewal-percent-threshold: 0.85       # ??????????????????
    response-cache-update-interval-ms: 3000 # ????????
    wait-time-in-ms-when-sync-empty: 0  # ????????????????????

# ??????
logging:
  level:
    com.netflix: warn
    org.springframework.cloud.netflix.eureka: info
    org.springframework.boot.autoconfigure: error