spring:
  application:
    name: rockectMQTest
# rocketMQ
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # ????????
    enable-msg-trace: true
    # ?????????????group?????????????rocketmq???ip@pid?pid??jvm?????????
    group: "service-pay-producer"
    # ?????? ?? 1024 * 4 (4M)
    max-message-size: 4096
    # ??????????? 3000
    send-message-timeout: 3000
    # ?????????????2
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
server:
  port: 8081